### ISSUE TITLE
WARC extension gets converted to .gz instead of .warc.gz extension

### ISSUE THREAD

**Issue by ikreymer** [esmero/format_strawberryfield#126]
It seems that when a WARC that ends in .warc.gz is uploaded, it will be converted to default.gz and not default.warc.gz

Unfortunately, that currently breaks the replay, as .gz is not recognized as a valid extension, only .warc and .warc.gz.

Looks like that happens here: https://github.com/esmero/format_strawberryfield/blob/01b62cddf7f6cf9835a5a47548b9d357086ab83d/src/Plugin/Field/FieldFormatter/StrawberryWarcFormatter.php#L220

If its a .warc. or .warc.gz, it would be ok to just set it to .warc always, unless its a .wacz - hopefully a quick fix!

**Comment by DiegoPino** [comment]
@ikreymer thanks for reporting this. Yes, it is a quick fix for sure. Will commit with another pending WACZ pull I have in the making, should be solved by tomorrow!

**Comment by DiegoPino** [comment]
@ikreymer funny thing its actually not that trivial in PHP.  The way also mime type detection works is based on the last extension so its basically skipping al my tests.
So. Is a .warc file not .gz? Or are both extension interchangeable (like renaming the file) for the same source? Asking for a friend here.

This also affects tar.gz  of course.

I'm working on a solution that is robust-er now bc when you in the same Editing ADOs session and you upload two files with the same name, Drupal renames the second one adding an incremental number. But guess what. It adds the number between the warc and the gz breaking all my logic. 🤕 

mmmm

**Comment by ikreymer** [comment]
Just .warc should be fine too, and may even be preferred! Maybe it can just be renamed .warc.gz -> .warc somewhere..

Yes, the double-extension is problematic in many cases. Webrecorder tools usually offer .warc as download, even if gzipped, because double-extension is problematic in the operating system (usually ends up just opening with default tool for .gz files rather than with an app for warc files)

**Comment by DiegoPino** [comment]
Thanks!!! I will probably hardcode some exceptions instead of reinventing the wheel for tar.gz and warc.gz.

**Comment by ikreymer** [comment]
I guess ideal solution, if possible, maybe to store WARC as is and convert to WACZ on the fly. For small enough WARCs <500MB, it shouldn't take too long, and will make the replay faster right away.

**Comment by aksm** [comment]
Hi @ikreymer, closing this since it's resolved. Please re-open if you feel otherwise. Thanks!

**Comment by DiegoPino** [comment]
@aksm thanks to closing issues! When doing so could you add the 
"resolved by link-to-the-merged-commit" as a message? That allows us to also be sure the issue was fixed by code. Thanks!

**Comment by aksm** [comment]
Resolved by esmero/strawberryfield#154.
