### ISSUE TITLE
Display information block throws an error when on a empty node context

### ISSUE THREAD

**Issue by pcambra** [esmero/format_strawberryfield#132]
When on node/add pages, `$node = $this->getContextValue('node');` returns an empty node which ends up trying to render a link without the relevant information it needs to be rendered and throws a PHP error:

```
Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "node" for route "format_strawberryfield.display_settings" must match "[^/]++" ("" given) to generate a corresponding URL. in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 204 of core/lib/Drupal/Core/Routing/UrlGenerator.php). 
```

Related to #120

**Comment by DiegoPino** [comment]
Related to #120

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/format_strawberryfield/commit/d92a27bca790fe8ad254b12341241aedb2f7601b

Thanks @pcambra !
