### ISSUE TITLE
Panorama tour, switch between scenes rises an error on mobile

### ISSUE THREAD

**Issue by giancarlobi** [esmero/format_strawberryfield#175]
I have a strange error on some (not all) smartphone: the first panorama is viewed well but when I go to the second panorama, smartphone get an error:
![image](https://user-images.githubusercontent.com/4232178/138881818-462e4622-5d1d-409d-a592-881faf2b9d9b.png)
While if I open second panorama directly (not in tour) it is showed ok
I see that code checks for mobile and limits resolution in case, so it seems that when I go to second panorama mobile info is lost.
To temporary solve, I changed this line https://github.com/esmero/format_strawberryfield/blob/fcf1784792fd72ada5faf593a52adfc0f6592e93/src/Plugin/Field/FieldFormatter/StrawberryPannellumFormatter.php to limit to 8192 (instead of 16384). I know it's not the best way but avoid error at the moment.
@DiegoPino suggests "WebGL limits are not easy not catch. I can do a fix on the JS for this too,  but i can also make a setting to limit it directly per viewer if that helps."

**Comment by DiegoPino** [comment]
Solved. We can revisit if it happens again
