### ISSUE TITLE
Make IABookReader view mode work with IIIF Presentation Manifest API 3.0 for both PDFs and creative work series

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#184]
This will entail reworking `plugin.iiif-iabookreader_strawberry.js` to detect the IIIF manifest version, and implementing a separate parsing pipeline for version 3.0.

To display creative work series using the book reader, it should be configured like this:
![Screenshot from 2022-04-01 16-41-59](https://user-images.githubusercontent.com/241240/161338615-845fc9d2-cbad-4ec7-9bdf-9dd7c34c9577.png)
![Screenshot from 2022-04-01 16-42-18](https://user-images.githubusercontent.com/241240/161338635-02ad0f17-82e2-4f98-8d98-9b301e212ce2.png)

To display PDF object documents should only require changing the display template like this:
![Screenshot from 2022-04-01 16-45-33](https://user-images.githubusercontent.com/241240/161339095-8047f163-24f1-46ae-b639-4d53aed6bc6b.png)

Supporting HOCR in creative work series that are displayed in the IABookReader will be another issue.

**Comment by DiegoPino** [comment]
@patdunlavey thanks. I already made a refactor of the IIIF Manifests involved to match this. Will commit to Deployment repos in 1.0.0 version by Monday. HOCR is already in the works.

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/format_strawberryfield/commit/1e87a72bb4b8cfca480e5659dffa51cdc258acf7
Thanks so much @patdunlavey for your great work on this. It is a delight to review your code! 🥳

**Comment by patdunlavey** [comment]
Thank you @DiegoPino !
