### ISSUE TITLE
CiteProc dependencies are extracted into the wrong folder

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#214]
# What?
b4e522bb1515a3c7be97ca8d7ee52b35f8c3b618 was accidentally reverted in a later commit on the same PR. CiteProc dependencies need to go in the vendor folder as noted in the commit.

**Comment by DiegoPino** [comment]
@aksm can you make the re-revert into #209 so we do not need to over-refactor?

**Comment by aksm** [comment]
This pre-dates #217, which was resolved by #218
