### ISSUE TITLE
ADO Type condition plugin

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#221]
# What?
- There is currently no way to condition block display or contexts on the ADO Type. 
- It would be useful to be able to condition the display of a block for digital_object_collections with type="Collection", for example.
# Proposed solution
- Create a `@Condition` plugin whose configuration form displays the available options for ADO type.
- See https://gitlab.com/davidjguru/drupal-custom-modules-examples/-/tree/master/visibility_conditions for a decent template to follow.

**Comment by DiegoPino** [comment]
Solved by mega-super @patdunlavey via https://github.com/esmero/format_strawberryfield/commit/400032147e9d7496bd33bc4f26d462ed91fbb281

Thanks!
