### ISSUE TITLE
Provide media/files at UUIDs additionally to node IDs

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#223]
# What
Related to esmero/strawberryfield#220 and esmero/strawberryfield#230.

When downloading media/files for ADOs they are currently accessed at unstable node IDs. As we do for the ADOs themselves, they should be provided at stable UUIDs.

The suggested path will be as follows:
`/do/{uuid}/file/{uuid}/download/{format}`

@DiegoPino Not sure if I'm describing this correctly so please correct me if I'm wrong or need to clarify.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/005b14a801400ed4b18950980ce525fc047e488a
