### ISSUE TITLE
Wrong default loaded (JSON Key...) and displayed in the embargo key

### ISSUE THREAD

**Issue by todhamma** [esmero/format_strawberryfield#226]
This line here

https://github.com/esmero/format_strawberryfield/blob/8f4a77212d4443212df8c72d980fca8fbb00d686/src/Plugin/Field/FieldFormatter/StrawberryBaseFormatter.php#L191

The data in` JSON Key(s) where the files to be used by this formatter where uploaded/store in your JSON` is being loaded in `When embargo is used or applied, alternate JSON Key(s) where the files to be used by this formatter where uploaded/store in your JSON.`
So, require to change it to `embargo_json_key_source`.

`'#default_value' => $this->getSetting('embargo_json_key_source'),`

**Comment by DiegoPino** [comment]
@todhamma thanks so much. Do you feel comfortable doing this change as your first pull request? @aksm and I are 🥳 Happy to help if so!

**Comment by todhamma** [comment]
Wow! Thanks @DiegoPino for the credit. 🥳 Sure.

**Comment by aksm** [comment]
Resolved by bae781428e25ed6c7d3786dcc34142de3be751f1.
