### ISSUE TITLE
Citation Formatter check for null

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#236]
# What?
`$rendered_json_string = $metadatadisplayentity->renderNative($context);` in `StrawberryCitationFormatter.php` needs a check before in case the metadata display entity being loaded is NULL.

**Comment by DiegoPino** [comment]
@aksm the check is there already, I think the issue is where this is called.

**Comment by aksm** [comment]
Resolved by 92a78e2ee1f3e70e46c514d3740d7a7331256853 and bea506e601f782c2d5767f33ec7996116a64d59a, for 1.1.0 and 1.0.0 branches, respectively.
