### ISSUE TITLE
Spacing error in format_strawberryfield.schema.yml

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#237]
# What?
The below section throws an error because it should be aligned with `type: mapping` just above it:
https://github.com/esmero/format_strawberryfield/blob/e278f711d7ee015dab4e2da781eaf2db9b7b1983/config/schema/format_strawberryfield.schema.yml#L385-L403

**Comment by patdunlavey** [comment]
Yep - just discovered this one too!

**Comment by DiegoPino** [comment]
Thanks. Fixing.

**Comment by aksm** [comment]
Resolved by 3af528457663395482f14c51cd428ce6be0053cd
