### ISSUE TITLE
Add clarifying text to Metadata Formatter using Twig settings form

### ISSUE THREAD

**Issue by marlo-longley** [esmero/format_strawberryfield#24]
### Why?
This is a small improvement based on discussion on the Archipelago user group [here](https://groups.google.com/forum/#!msg/archipelago-commons/z8ANSTORaRU/tqO57s-eCgAJ).
This form can be made easier to use.
<img width="1200" alt="Screen Shot 2019-10-19 at 2 18 11 PM" src="https://user-images.githubusercontent.com/1328900/67151863-0334b680-f281-11e9-939f-6fec6f8dc8a0.png">
- Add description to form
- Add description to the currently unlabled text field input to clarify user interaction.
- Fix so that the label field shows (currently not showing bc wrong field type)

I also feel that the label in the dropdown may be confusing - "Metadata Formatter using Twig". The Twig part is not so relevant in this form, just the fact that you are selecting a template. We know it is Twig behind the scenes and that is cool! And relevant when designing the Twig template. But not here? Could be information overload for user and it confused me at first, personally. Suggestion: "Strawberry Field Custom Metadata Template."

**Comment by DiegoPino** [comment]
@marlo-longley great. I like this smaller Issues and pulls. Easier to review and fast to get into the code. Thanks!

**Comment by marlo-longley** [comment]
@DiegoPino This small task is making me think about how selecting a custom metadata template (whether one we code into the our deploy.sh, or one the user creates) is almost a whole different feature than selecting Audio, 3D, Book Reader, even though they are all "Formatters" behind the scenes. I am making notes on that idea!

**Comment by DiegoPino** [comment]
Yes. Because, as you have seen (but maybe you are not aware yet) we are using this formatter also as a View driven block in every DO. Means, not every time, formatters get triggered by a View Mode, but it could be also driven by a View, using a Block display, where we implicity ask the View to render the field_metadata_display using that formatter. See http://localhost:8001/admin/structure/views/view/ld_display_for_digital_objects_sql?destination=/admin/structure/views

**Comment by marlo-longley** [comment]
Cool yes. I guess, I feel like the other media formatters would be used when creating displays/exhibits of objects. Whereas the metadata templates would be used as part of migrations or more technical tasks, where the user would be using Archipelago as a utility almost. So maybe part of whole different workflows/use cases. Less about the technology. Just something to think about for UX later.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/1f00b097bd12913ed1edb9d294f2c9eb43808365
