### ISSUE TITLE
Ado type condition plugin breaks block visibility form

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#249]
When editing a block, the `required = TRUE` attribute for the  'ado_type' form element causes form submit to fail, with `An invalid form control with name='visibility[ado_type_condition][ado_types]' is not focusable.` message in the console. It also causes a context condition form to fail to submit if the "ADO Type" is not entered and the tab is not visible.

I think the solution is simply to remove [line 65 of Plugin/Condition/AdoType.php](https://github.com/esmero/format_strawberryfield/blob/1.1.0/src/Plugin/Condition/AdoType.php#L65). There is no purpose that I can think of in making this field required. If you fill it in, great, if not, then the evaluate condition will normally return true (unless you check "negated"). So I don't think there's any harm in just removing the "#required" attribute.

Do you agree @DiegoPino ? Shall I make a PR?

**Comment by patdunlavey** [comment]
PR Created: https://github.com/esmero/format_strawberryfield/pull/250

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/format_strawberryfield/commit/fa73dba305ee2bfb1c8f7cfc7f9a709368cb702a
Thanks @patdunlavey!

**Comment by patdunlavey** [comment]
Thanks @DiegoPino !!
