### ISSUE TITLE
explore subpathauto for do/uuid paths

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#25]
# What?
All our ADOs are using yoursite.edu/do/uuid as canonical path to access instead of the non sense /node/1 thing. We need and we want UUIDs and even if we can override programatically the entity resolver, right now it seems easier to have path alias programmed to do that. We do it and it works. But! Path alias does not expand, existing aliased paths for subpaths.

Like /do/uuid/metadata/iiifmanifest does not resolved automatically. Since out metadata exposed endpoints are dynamic (good!) we want to access them also via the uuid path.

There is this little module named

https://www.drupal.org/project/subpathauto

# Task 
- Explore if it does a good job
- IF the code is sustainable and needs to be checked to be compatible with 8.8 and 9.0 alpha
- IF yes, make it part of archipelago-deployment (beta2), if not, see how we can bring the functionality into our own scope

@giancarlobi @marlo-longley what do you think?

**Comment by giancarlobi** [comment]
@DiegoPino I really prefer dynamic url added to the ado uuid (i.e. /do/uuid/metadata/iiifmanifest) instead of (as Islandora 7) endpoint url with added ADO uuid (i.e. /metadata/iiifmanifest/do/uuid).
So, yes we have to explore subpathauto (if reliable) or add code to provide that.

**Comment by DiegoPino** [comment]
Great! Thanks @giancarlobi. Do you think you could test subpath in the next weeks? I know you are super busy so if not can do it myself or ask @marlo-longley

**Comment by giancarlobi** [comment]
@DiegoPino I'll try next days to give it a chance. I keep you informed. Yes, really busy, new switch core arriving and network and vlans to redesign ...

**Comment by DiegoPino** [comment]
@giancarlobi i tested and it does not work. Not sure if its me, or documentation is just missing explanations. It has a setting to enable what depth the autoalias should go to enable subpaths but i went as far as the maximum (with performance hits) without luck.

My solution is:
Make our route start with /do
change the entity resolver (custom) to use uuids as arguments.
Will require extra code i guess!

**Comment by DiegoPino** [comment]
@giancarlobi @marlo-longley i'm now writing a something in the tone of this.
https://git.drupalcode.org/project/jsonapi/blob/8.x-2.x/src/ParamConverter/EntityUuidConverter.php but directly on strawberryfield. Not working right now of course (because well, its complicated) but the idea is that i want to allow UUID to be used as yet another way of loading entities when having a /do/ route. To be able to do that i don't want to have to rewrite the routes and create a custom processor, i just want the upcast to happen automatically. So i will close this one as "won't fix" and will create a new Issue inside SBF. Thanks
