### ISSUE TITLE
Internet Archive Bookreader mobile menu is broken

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#262]
# What?
When using the Internet Archive Bookreader the responsive hamburger menu isn't triggering as expected on appropriately sized windows.

**Comment by aksm** [comment]
This took far longer than I expected to debug, but it turns out that we're missing the corresponding CSS for the following:

https://github.com/esmero/format_strawberryfield/blob/37c90b6d042fd0264748a40cf3859bccf5ce6f9a/format_strawberryfield.libraries.yml#L44

Will need our own additional CSS to match our theme. More to come.

**Comment by DiegoPino** [comment]
wonderful! good catch!!

**Comment by aksm** [comment]
Resolved by #263 and #264.
