### ISSUE TITLE
Allow Video and Audio take any VTTs if there is a single source. Make the "default" behavior a setting

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#269]
# What?

Right now I made a decision (sorry @alliomeria ) to fetch Video/Audio and VTTs grouped by upload element on the Audio/Video players.
Means if the VTT is an a different key (upload) than the media it does not get selected.

I can change that https://github.com/esmero/format_strawberryfield/blob/3941ccef610f3c87f55944985ec2805b2c6c012c/src/Plugin/Field/FieldFormatter/StrawberryAudioFormatter.php#L241

And allow a default behavior in case of e.g a single Media and single/multiple VTTs to not care about that. 

Will also add a setting to define the default behavior so people can also disable this if it gets messy

**Comment by alliomeria** [comment]
Sounds great, thank you @DiegoPino !

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/format_strawberryfield/commit/3200a40445597fc2630f297e8d94b5df700a4759
