### ISSUE TITLE
Report render array output error in Metadata Display preview

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#274]
# What?
When a render array output is generated via a metadata display template, e.g. `{{ data.ia_an_array_dont_uoutput_me }}`, the error (see screenshot below) is not reported in the preview.

![render_array_error](https://user-images.githubusercontent.com/15711380/219756851-a6924ae5-30f9-4bc8-8df5-3f241ee4f318.png)

Todo:

* Add a report of the KEYS used in the template v/s the JSON (basically a coverage of their use of values (from the source) in the output).
   1. Get all keys on the selected ADO
   2. Check their type (single value, iterable)
   3. Rename them to data.thekeyname in a function
   4. Parse the Twig checking how many times thekeyname is mentioned or attribute(‘thekeyname’, data) and in which lines
 
See for reference (no longer working due to changed interface): <https://github.com/esmero/format_strawberryfield/blob/2e5cc2a6f882cd2490caccc2cbd5b88b58f70c0f/src/Entity/MetadataDisplayEntity.php#L435-L459>

**Comment by DiegoPino** [comment]
Solved for main preview via https://github.com/esmero/format_strawberryfield/issues/274
@aksm we need an issue that matches this one on AMI!
