### ISSUE TITLE
Add/Remove for Advanced Search doesn't work when the operator is not exposed

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#276]
See https://github.com/esmero/format_strawberryfield/issues/260#issuecomment-1452142415.

When the exposed advanced search form is built/rebuilt [here](https://github.com/esmero/format_strawberryfield/blob/2e5cc2a6f882cd2490caccc2cbd5b88b58f70c0f/modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php#L667), it only adds/removes filter fields if the form elements are contained inside a wrapper div. 

However, the wrapper element is only created "When the operator and value forms are both in play": https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/views/src/Plugin/views/filter/FilterPluginBase.php#L961.

This task is to make add/remove work, whether or not the exposed filter operator is exposed.

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/format_strawberryfield/commit/b3571c01558493abde3af2b92e8b6cfc9406be9f by @patdunlavey . Thanks
