### ISSUE TITLE
Labels for SBFs in Manage Display are misleading

### ISSUE THREAD

**Issue by marlo-longley** [esmero/format_strawberryfield#30]
### Background

![Screen Shot 2019-10-29 at 9 46 50 AM](https://user-images.githubusercontent.com/1328900/67789419-2c97d400-fa31-11e9-8e40-58e1b7252f01.png)

In the Manage Display tab for Digital Objects we show 1 SBF and 3 copy fields of SBF from Display Suite. It's possible to add/delete these fields at `/admin/structure/ds/fields`.

### What is Wrong?

Nothing functionally, but the labels are misleading, since all these fields are actually just SBFs (well, copies). So "Static Media" is the same as "Formatted Object Metadata" and any SBF Formatter can be used.

###  Fix

Just change the labels. Suggestion "Strawberry Field Data"
In the future, maybe we will actually restrict/suggest formatter options based on media, display mode, or other factor, but for now just clarify.

Thoughts!

**Comment by DiegoPino** [comment]
@marlo-longley is this something you are willing to put an hour or so to fix? Or just part of the wishlist? Thanks!

**Comment by marlo-longley** [comment]
@DiegoPino Yes can a stab this week!

**Comment by marlo-longley** [comment]
@DiegoPino I don't know the best way to push this, other than changing config files in `/sync`, and I am not sure this is a good practice.

**Comment by marlo-longley** [comment]
Update, will wait to push for beta-2 with new config files later in the week.

**Comment by DiegoPino** [comment]
Fixed since RC1. We use strawberries, emojis and labels in multiple languages. Also always a config issue, not here
