### ISSUE TITLE
Advanced search - white screen when aggregated filter combined with non-aggregated

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#304]
When performing an advanced search where an sbf aggregated fulltext search is combined with a content field fulltext search, I get...
```
The website encountered an unexpected error. Please try again later.
TypeError: Drupal\search_api_solr\Utility\Utility::flattenKeys(): Argument #2 ($fields) must be of type array, bool given, called in /var/www/html/web/modules/contrib/format_strawberryfield/modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php on line 422 in Drupal\search_api_solr\Utility\Utility::flattenKeys() (line 748 of modules/contrib/search_api_solr/src/Utility/Utility.php).
Drupal\search_api_solr\Utility\Utility::flattenKeys(Array, , 'terms') (Line: 422)
Drupal\format_strawberryfield_views\Plugin\views\filter\AdvancedSearchApiFulltext->query() (Line: 1378)
```

The problem seems to be here: https://github.com/esmero/format_strawberryfield/blob/1.1.0/modules/format_strawberryfield_views/src/Plugin/views/filter/AdvancedSearchApiFulltext.php#L421, where `$query_able_datum_fields['aggregated']` should be `$query_able_datum_internal['aggregated']`. The state of `$query_able_datum_internal['aggregated']` on this line is whatever it was left in the earlier foreach loop.

If it helps make this clearer, here is an example what the url parameters look like:
`?sbf_advanced_search_api_fulltext=Amherst&sbf_advanced_search_api_fulltext_searched_fields=sbf_aggregated_items&sbf_advanced_search_api_fulltext_advanced_search_fields_count=2&sbf_advanced_search_api_fulltext_group_operator_1=and&sbf_advanced_search_api_fulltext_1=december&sbf_advanced_search_api_fulltext_searched_fields_1=title`

**Comment by DiegoPino** [comment]
@patdunlavey makes sense! I'm trying to figure out why in the hell all my sites that have this enable don't have this issue. it might be a coincidence (bad on me) that the state of $query_able_datum['aggregated'] (bc it was the last field?) was always correctly primed?

Please make a pull request (I mean change the code locally and test to see if it works) but it really makes sense what you describe. If you can add a check if the value is actually an array before passing even better.

**Comment by patdunlavey** [comment]
Will do first thing tomorrow. Thanks!

**Comment by DiegoPino** [comment]
Thanks to you!

Diego Pino Navarro
Director of Digital Strategy
Archipelago architect
Metropolitan New York Library Council
PO Box 2084
New York, NY 10108

**Comment by patdunlavey** [comment]
PR created: https://github.com/esmero/format_strawberryfield/pull/305

**Comment by DiegoPino** [comment]
Fixed by @patdunlavey via https://github.com/esmero/format_strawberryfield/commit/afdac188da8e824d907cf6f0b9b215f3ae43629a

Thanks Pat!
