### ISSUE TITLE
Wrong null coalescing operator order/priority in Facet/Date Range

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#308]
# What?

mtenney (not sure if Martha has GitHub profile) trigged and reported a bug related to resetting a Date range when there are no results. Because we have to process manually the originally passed values that lead to no results (Drupal looses Facets when this happens) I added this here to deal with a 0 date range

https://github.com/esmero/format_strawberryfield/blob/afdac188da8e824d907cf6f0b9b215f3ae43629a/modules/format_strawberryfield_facets/src/Plugin/facets/processor/DateRangeProcessor.php#L165-L166

But!

I got it wrong

It needs to be 

```PHP
 $min_unix = (int) ($range_entry['min'] ?? 0); 
 $max_unix = (int) ($range_entry['max'] ?? 0);
```
Because casting to INTEGER will execute before the null coalescing operator leading to an attempt to access a non existing `$range_entry` key

Tested on a live system and this fixes it. @alliomeria yet another bug turned into a pet.

**Comment by aksm** [comment]
Resolved by 585a604beacc1ab38fe7d5a3ed7025bfa625d6c4.
