### ISSUE TITLE
Twig template label is null when adding templates

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#318]
# What?
While investigating/testing #315, I got this error:

> TypeError: Twig\Source::__construct(): Argument #2 ($name) must be of type string, null given, called in /var/www/html/web/modules/contrib/format_strawberryfield/src/Entity/MetadataDisplayEntity.php on line 423 in Twig\Source->__construct() (line 30 of /var/www/html/vendor/twig/twig/src/Source.php)

The label is null here for newly added templates:
https://github.com/esmero/format_strawberryfield/blob/74d68f93099ec2c94976797f33dbe86b58e53a40/src/Entity/MetadataDisplayEntity.php#L423

I guess I had never tested `getTwigVariablesUsed()` while adding a new template? Or something else has changed? Will investigate further.

**Comment by DiegoPino** [comment]
@aksm, sadly there are too many issues in SBF related to this new piece of code. I can not get around deprecation errors rendering but e.g not triggering views on templates and it is not clear to me if Pat's comment is or not valid + plus this one. This piece of archipelago is core. I will try (12AM here) to revert the changes to a previous state in a while. And when I come back we will have to re-work the code into archipelago. Won't remove the actual getVariables code from the entity itself but I will remove the usage on the preview. We talked about this with @alliomeria and we agree stability wins here. Thanks

**Comment by DiegoPino** [comment]
resolved via https://github.com/esmero/format_strawberryfield/commit/663b0fa0987738adbc8c451c11d55322dccb75b0
