### ISSUE TITLE
Formatters using StrawberryDirectJsonFormatter.php produce an AJAX error when using with Layout Builder

### ISSUE THREAD

**Issue by wwu-webtech** [esmero/format_strawberryfield#323]
When attempting to use Warc Formatter, Audio Formatter, or Video Formatter for Strawberry Descriptive Metadata Fields inserted via layout builder, an AJAX error is produced:

![Screenshot 2023-06-15 at 9 31 10 AM](https://github.com/esmero/format_strawberryfield/assets/133159473/d483950d-3157-47fa-8433-329876fd62d0)

![Screenshot 2023-06-15 at 9 31 18 AM](https://github.com/esmero/format_strawberryfield/assets/133159473/44049aa5-9807-4faf-83b7-b596444fa4b4)

This error points to the [FieldFormatter/StrawberryDirectJsonFormatter.php](https://github.com/esmero/format_strawberryfield/blob/e360aca0dfc1b68f4740dfa9c1ff8e76cc82aca2/src/Plugin/Field/FieldFormatter/StrawberryDirectJsonFormatter.php#L65-L66) as the source of the issue for all three formatters.

None of the other formatters present this issue when selected.

**Comment by DiegoPino** [comment]
See #324 tested in Layout Builder mode, DS Mode and no mode at all (Vanilla View Mode). Validation for JMESPATH works and JMESPATHS are saved correctly

**Comment by wwu-webtech** [comment]
The update worked and this issue was fixed for us 👍

**Comment by DiegoPino** [comment]
Added https://github.com/esmero/format_strawberryfield/commit/c78d618a4ac9ce726f71f1c3653072a79782bcc7 to fix missing arguments Layout Builder adds (via route alters) for View Mode Edit forms
