### ISSUE TITLE
Custom error handler needs to filter out unhelpful errors/deprecations

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#338]
# What?
Related to #320. The custom error handler was throwing exceptions on unrelated errors and deprecations, which were being reported to an end user (who wouldn't be able to do anything about it) editing metadata templates. We should limit these to only what's useful for editing/creating templates.

**Comment by DiegoPino** [comment]
Resolved to https://github.com/esmero/format_strawberryfield/commit/26ac3add3da97d2c5410fdc3b368d605d3fb9f6a
