### ISSUE TITLE
Typo in format_strawberryfield_rest_oai_pmh\Form\FormatStrawberryfieldRestOaiPmhSettingsForm::buildForm.

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#357]
PR: https://github.com/esmero/format_strawberryfield/pull/356

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/bea6d598ef21c69dd3a73275068e7cbe15037664
