### ISSUE TITLE
Metadata Display Preview Codemirror output visually inconsistent

### ISSUE THREAD

**Issue by aksm** [esmero/format_strawberryfield#358]
# What?
esmero/ami#166 includes a commit to make the Codemirror output consistent with the Details tab for the HTML output in the Preview section. The same element just needs to be copy here.

**Comment by DiegoPino** [comment]
Resolved by https://github.com/esmero/format_strawberryfield/commit/608df948dc802fabdf84e5f687e020b818febcc8
