### ISSUE TITLE
Allow saving annotations in the view mode

### ISSUE THREAD

**Issue by fishfree** [esmero/format_strawberryfield#379]
Now, we must Edit the ADO and then save the annotations. This is not intiutive.

**Comment by DiegoPino** [comment]
@fishfree there are many good reasons for keeping the view mode free of "saving" interactions, including race conditions of a JSON patch operation that could happen if multiple users save annotations at the same time (plus the fact that we inherit Drupal security in the "edit" screen). If you believe this can be improved happy to review a code contribution from you. You will need a controller/Ajax-JS/access check and UI attached provided by the formatter. The logic itself can be borrowed from our form alter in the main module. Not complex to do. Thx

**Comment by DiegoPino** [comment]
Closing as won't fix for now. Contributions (code) are welcome if someone needs to be tackled for the next release
