### ISSUE TITLE
IA Bookreader: permit configuration of default page mode

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#417]
Not sure if I'm just missing a trick here, but currently IA Bookreader always defaults to the 2-up page display mode. I'd like to be able to configure the default page mode (1up, 2up, thumbs) in the \Drupal\format_strawberryfield\Plugin\Field\FieldFormatter\StrawberryPagedFormatter::settingsForm, and then reflect that setting in the default behavior of the bookreader when it loads a book manifest (absent the `#page/NN` fragment in the url).

**Comment by patdunlavey** [comment]
The config part is easy, but I'm struggling with the bookreader behavior part. If you have any pointers @DiegoPino , please let me know!

**Comment by DiegoPino** [comment]
@patdunlavey this issue here:
https://github.com/esmero/format_strawberryfield/issues/292

Is a better option than a fixed setting

**Comment by patdunlavey** [comment]
Ok, sending the page mode hint into IAB via the IIIF manifest makes sense to me. I particularly like the idea that you could have different hints per canvas. I'm thinking we should close this issue as superseded (preceded, actually!).
