### ISSUE TITLE
Entity query access check needed in TwigExtension::entityIdsByLabel

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#447]
Need to add `$query->accessCheck(FALSE);` right [here](https://github.com/esmero/format_strawberryfield/blob/1.4.0/src/TwigExtension.php#L145).

PR coming...

**Comment by DiegoPino** [comment]
@patdunlavey cool. Thanks!

**Comment by patdunlavey** [comment]
I almost always default to (FALSE) in these cases since that emulates the D9 behavior. Changing to (TRUE) could generate a regression, and should be more carefully evaluated. Do you object strongly to leaving it as (FALSE)?

**Comment by DiegoPino** [comment]
@patdunlavey we don't use that extension or have used with any partners for that reason. I can see a point towards security being done there if used blindly with FALSE. Access to unpublished nodes, etc. 
For me the most concerning entities there are
"node" and "user"... so maybe adding access(TRUE) if one of those?
That all said, the function returns IDs... so basically once you try to load them/use them in any other way permissions will kick in anyways. 
What is your current use case/need of this one? Vocabularies?

**Comment by DiegoPino** [comment]
Means I don't strongly object to FALSE, but want to be sure that if I have to make it TRUE in the future I will not break every site you have

**Comment by patdunlavey** [comment]
We're using it in AMI set processing to convert strings to their corresponding taxonomy term ids. I *think* setting it to (TRUE) will be fine, but I don't want to be wrong and have to spend a lot of time sorting it out.

**Comment by DiegoPino** [comment]
performance should not be an issue really, because the ::access() just adds under the hood a query condition, does not really load the entity but ok, let's keep it FALSE and I can write some if "node" alternatives later (taxonomies are kinda safe IMHO) but add (can you add a title to your pull too) a note to the Pull request so we can revisit this in the future? Thanks. Once you do that I can merge. If you need this backwards 1.3.0 please make a pull against 1.3.0 too, but given how different drupal 10.2 is to 10.1 I think 1.4.0 should be ok

**Comment by patdunlavey** [comment]
I just did some double-checking the above-described AMI set use-case, and I'm satisfied that it's safe to set the accessCheck to (TRUE). We don't use this twig function anywhere else, but if we did, I think it's reasonable to impose the check in those cases. So I'll make that change in the PR. If that causes anybody difficulty, they can raise a new issue!

**Comment by patdunlavey** [comment]
I'm fine with this being limited to 1.4.x, since the D10 accessCheck requirement comes with 1.4.x.

**Comment by DiegoPino** [comment]
Appreciate your work and feedback. Ready to merge!

**Comment by DiegoPino** [comment]
Solved (so far, ping me if not/adds creep to Hydroponics AMI processing) via https://github.com/esmero/format_strawberryfield/commit/56e7a27052a467fa5e30c1e17ee16718dbfda008 by @patdunlavey . Thanks!

**Comment by patdunlavey** [comment]
FYI @DiegoPino I tested an AMI ingest with background processing via hydroponics, (cron activated by curling drupal cron), and the access check was fine - the objects updated their taxonomy term fields correctly.

**Comment by DiegoPino** [comment]
Wonderful! Thanks for reporting back
