### ISSUE TITLE
Better Metadata API Views argument/contextual filter and exposed filter handling

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#449]
# What?

When the Open API accesses multiple Contextual filters, the order of those need to match exactly all existing ones. So that only happens if all are mapped/passed as arguments but not when one is present the other not.  This could be also avoided by having better Exposed filter matching but the idea is to allow both well (gosh)

@alliomeria I have to fix this during the morning. Will keep you updated. Thanks

**Comment by alliomeria** [comment]
Thanks to you @DiegoPino !

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/format_strawberryfield/commit/5e1a046c5437538c79262aae9b5b531d408efb7d
