### ISSUE TITLE
Mirador Overrides 

### ISSUE THREAD

**Issue by alliomeria** [esmero/format_strawberryfield#453]
# What's happening:

When's using `JSON with Mirador Viewer configuration overrides`, some override parameters are not being respected (such as `{ "window": { "thumbnailNavigation": { "defaultPosition": "far-right" } } }`).

As seen during local tests by myself & @DiegoPino.

**Comment by DiegoPino** [comment]
@alliomeria on it!

**Comment by alliomeria** [comment]
Awesome, thanks @DiegoPino !

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/63570d92737066d91dca3b26b3265b141794ecf0
