### ISSUE TITLE
Settings Summary not updated on change in Display Suite copyfields

### ISSUE THREAD

**Issue by marlo-longley** [esmero/format_strawberryfield#46]
### What's wrong?

Found a bug on the Manage Display page here: `/admin/structure/types/manage/digital_object/display`

When using the select dropdowns to select formatter. The settingsSummary changes if you are using the dropdown for the ACTUAL field (in the current version, this is labeled "Metadata Display").
To reproduce:
1. For the Metadata Display field/row, make a new formatter selection from the dropdown, and the appropriate settingsSummary appears.
2. Pick any of the other three fields/rows (copyfields). For example, "Formatted Object Metadata". Change the dropdown value. The settingsSummary will not be updated.

### Ideas:
Thoughts from @DiegoPino pasted below:

The problem seems to be in the drupal/ds module.

My quick research shows me that https://git.drupalcode.org/project/ds/blob/8.x-3.x/includes/field_ui.inc#L1283-1299 could be the culprit. That or/not playing well with
/Users/dpino/Desktop/Development/esmero/esmero-docker/release-8.x-1.0-beta1/archipelago-deployment/web/core/modules/field_ui/src/Form/EntityDisplayFormBase.php
Where the swapping and Dynamic change via Ajax is happening. Is this something you can to research?

The workaround is "select", save, come back and edit the settings. But i feel we can patch this.

**Comment by DiegoPino** [comment]
Resolved since 2020
