### ISSUE TITLE
Remove hard-coded ado type field in ado type to view mode mapping form

### ISSUE THREAD

**Issue by patdunlavey** [esmero/format_strawberryfield#481]
I think this is really simple...
Change https://github.com/esmero/format_strawberryfield/blob/1.5.0/src/Form/ViewModeMappingSettingsForm.php#L224-L232
to...
```
    $field = $this->config('strawberryfield.archipelago_solr_settings.ado_type')->get('field') ?? 'type_1';
    $facets = [
      'type' => [
        'field' => $field,
        'limit' => 50,
        'operator' => 'AND',
        'min_count' => 1,
        'missing' => TRUE,
      ],
    ];
```

Is there any reason not to do this, @DiegoPino ?

**Comment by DiegoPino** [comment]
not really. legacy decisions. GO for it

**Comment by DiegoPino** [comment]
But it is not "hard" set ...
It is the default ... IF $this->config('strawberryfield.archipelago_solr_settings.ado_type')->get('field') is not get ...

**Comment by patdunlavey** [comment]
I'm not sure I understand  your second comment. Something you think I should do different?

**Comment by DiegoPino** [comment]
@patdunlavey please ignore my comment. I have too many open windows. Saw your suggestion and thought we were already doing it like that! (bc that was the original idea).

There are a few things we could improve for this form though (as you suggested in your pull) based on the fact that really the facet/selector is just a suggestion for already ingested types, and one basically could just use the "!" (the empty facet) to add "types" and mappings upfront before even ingesting anything (desired, specially if you are planning on controlling a bit what type of things people will eventually add), but this is already good.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/format_strawberryfield/commit/95ae15f39af56108a11804cf0b6dd7a54b4cabfd
