### ISSUE TITLE
Add missing schema

### ISSUE THREAD

**Issue by marlo-longley** [esmero/format_strawberryfield#54]
## What is the problem?

We have a lot of schema errors related to the format_strawberryfield repo. Many of them are related to formatters being applied to `display_field_copy` fields. You can see the errors at http://localhost:8001/admin/reports/status

## How to fix
Add schema into `format_strawberryfield.schema.yml`, clear cache, refresh, and see the errors disappear from the status report ;)

**Comment by DiegoPino** [comment]
jajaja

**Comment by marlo-longley** [comment]
@DiegoPino this one is the biggest offender in terms of the list. Push coming soon.

**Comment by aksm** [comment]
Resolved by #63.
