### ISSUE TITLE
Reorder "Next" & "Previous" Buttons in PDF Viewer

### ISSUE THREAD

**Issue by mitchellkeaney** [esmero/format_strawberryfield#69]
### What to do-a-do

The order of the buttons on the PDF Viewer are order as "Next", "Previous" and it would be nice if they were ordered as "Previous", "Next" - which is a little more intuitive and follows other image-viewer standards.  

◀️ 🚂 ▶️

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/format_strawberryfield/commit/470e89b1aaa5c3ba665e960fba5ff6a7f72ed486
