### ISSUE TITLE
Relationships between Files, VTTs and other issues: help needed

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#77]
# What is this? this is a question/discussion and i need some help

Related to https://github.com/esmero/webform_strawberryfield/issues/27

In that issue i formulated (without definitive code yet) the need of having an upload webform element field, or a standalone tab for Objects that allows users to `tag` files, reorder them, etc.

That needs is not empty or just a wishful idea. Its actually with practical implications but also a mayor workflow question. I will start by exemplifying

# Use case

## I want to upload an Audio File with a Transcript
- Current scenario
I. I modify the webform to allow a VTT file upload for Music/Podcast (reminder:we need to add also an JSON type: Interview option too!)
II. I Create a new Digital Object, Choose Podcast, fill the metadata, reach the Upload Step, Upload a MP3 and a VTT file. 

Situation:
- At that Stage the JSON will not yet contain an `as:audio` and `as:text` JSON keys, because those are generated when persisting the files. WE will only have one for the audio key upload (with an array of integers, File IDS, and one for the VTT, with an array of integers, the FILE IDS. In this case, every key will have just one value). I will say this loud. maybe the solution is that `as:audio` and an `as:text`,`as:image`, etc are all created inmediatelly and can be edited/enriched via a special webform element that i have YET TO CREATE.

- We can assume that if there is a single VTT and single Audio, that they should be displayed together in the Audio Player?
- We can code an audio Player and option that allows people to always use files where the name (without extension) match together? 
  - Question: Should we make like a regular expression matcher so things like: `myaudio.mp3` would match `myaudio-es.vtt` or `myaudio-01.vtt`. Via this i have no way of tagging the files as language `es` which is desired. Which leads to: i would like to have a `File Property editor in the webform so i can add this extra data` and the extra question of `if i do that` how to i tell `as:audio` extra data is coming from that one? maybe some Setting? And if so, where so it also applies to ingest via JSON API?

- We can code into the audio Player an option that plays all text/vtt files that it finds? (via mimetype?)
   - Question: would this be a switch in the formatter option?
   - Question: Should formatters also have some PHP method that allows them to say: Hey, i can play this mime types?
- We can code into the audio Player it should only play files where the `tag` key, which we don't have a way of assigning yet via the webform match?
   - Question: how do we assign Tag keys before `as:audio`, etc,  exist and where in the JSON? Would the tagging webform element be its own element with an array with a FID and an array of possible tags? In that case, makes it even sense to have `tags` key inside  `as:audio`, etc?

So, as you see i have a lot of practical questions and i guess i'm not giving people enough info. Anyone want's to give me a hand? @mitchellkeaney @giancarlobi ?

**Comment by giancarlobi** [comment]
@DiegoPino Some thoughts. 
- we have 1 audio file and 1 or more VTT files, right?
- if so, the master (parent?) is the audio file that could or not have child VTT files
- I think this is related to relationships, obviously
- in this case I suggest a fixed TAG to relate parent to child(s)
- probably the more simple solution is TAG into as:audio
- but we don't have as:image when we upload VTT 
Finally, what about a runner to make relationships (add TAG to as:image) and also probably a good idea upload by runner the VTT files? That is, I ingest audio object then call runner passing to it a zip with VTT files and the runner add TAGs into as:image.
Just an idea following Archipelago runner philosophy.

**Comment by DiegoPino** [comment]
@giancarlobi sorry for my late response. I'm taking 2 sick days. Will come back tomorrow with a follow up here. Probably my main issue is writing a proper UI for tagging, which leads to also a proper UI in general for file managment and file ordering outside of the webform workflow. I need to think deeper about this and will ask you to discuss/critic/destroy my ideas so we can come to something simple enough that works. But more tomorrow. Cheers and thx

**Comment by mitchellkeaney** [comment]
also sorry for my tardy response here! i have been trying to think of suggestions while also digest the scenario + engineering solutions, but to be honest I am unable to come up with anything that isn't what you or Giancarlo have suggested here.

**Comment by DiegoPino** [comment]
This is solved. Formatters prefer bundled media (same upload key) but also IIIF Manifests can drive relationships, e.g using Mirador 4 for video/subtitles
