### ISSUE TITLE
Make field formatters more flexible =  less number of Display Modes

### ISSUE THREAD

**Issue by DiegoPino** [esmero/format_strawberryfield#9]
# USE CASE

As discussed with @giancarlobi field formatters, because of its static nature as config entities, can have a set of setting per display mode to define the way they interact and process our JSON values. But, sometimes the same display mode (Lets name it "Display Object as a Book") could apply to various shapes of books. One with a IIIF manifest generated on the fly by our Metadata Display machinery and others if an external IIIF manifest URL exists inside the metadata.

# Discussion

- What would be the best level of flexibility versus too complicated to setup we could afford?
- Should we solve this in a case by case basis or should be design for this use case?
- What other Drupal modules that expose a reasonable UI can we reuse, rules, context, etc to help in this?
- Could we simply add a conditional that says "if this is true then don't process" and in that case having many formatters of the same type in a single Display Mode, each one with disjunct conditions (i mean 2 book formatters for the same display but one shows and the other not), all coming from the same JSON do the trick? More over, could be generalize that functionality as a preprocessor for all our formatters?

Totally open to ideas, i would really love to avoid having 50 display modes, but on the other side i would prefer that over a 50 elements config form for each field formatter.

**Comment by giancarlobi** [comment]
Finally I think that multiple display modes is not so bad, more clear for the user and more linear the code. If there are no Drupal performance problems, for book we can have 3/4 display modes in the worst case, so at this moment I give a +1 for multiple display modes.
